</div>  
  <footer>
    <div class="footer-left">
      <img src="images/logosmall.jpg" alt="IT Solutions Logo" class="logo">
      <p>IT Solutions &copy; <?php echo date('Y'); ?></p>
    </div>
    <div class="footer-right">
      <a href="https://codecrafterscollectivegrouptask.atlassian.net" target="_blank">
        <img src="images/jiralogo.png" alt="Jira logo">
      </a>
    </div>
  </footer>
</body>